services:
  db:
    image: postgres:16.3
    restart: always
    container_name: postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5431:80"
    depends_on:
      - db

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8083:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DN="${LDAP_DN}"
      - LDAP_PASS="${LDAP_PASS}"
      - LDAP_SEARCH="${LDAP_SEARCH}"
    depends_on:
      - db

#Change this to host folder on linux/unix OS, on windows there is trouble with folder permission and Docker volume is recomended (That is why I used it this way)
volumes:
  pgdata:
