# Generated by Django 5.0.6 on 2024-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifterslogin', '0005_shift_auto_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='modal_check',
            field=models.BooleanField(default=False),
        ),
    ]
